version: '3.7' # composeファイルのバーション指定
services:
  log-api: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/github.com/nakajimakota/log-api # マウントディレクトリ指定
    ports:
      - "8011:8011"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: go-log-api
    ports:
      - 5432:5432 